<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gcm</string>
	</array>
	<key>name</key>
	<string>Gekko</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#commands0</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#commands1</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#linecomment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#singlequotestring</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#math</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>commands0</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b((?i)READ|WRITE|EXPORT|OPEN|CLOSE|CLONE|DOWNLOAD|COPY|RENAME|INDEX|COUNT|COMPARE|FINDMISSINGDATA|UNSWAP|HDG|SHEET|TIME|OPTION|CLEAR|RETURN|STRING|x12a|freq|RESTART|MODE|SERIES|END)\b</string>
			<key>name</key>
			<string>keyword.commands0.gekko</string>
		</dict>
		<key>commands1</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b((?i)FILE|IMPORT|TIMEFILTER|CREATE|DELETE|COLLAPSE|SMOOTH|SPLICE|TRUNCATE|ANALYZE|DOC|LIST|DATE|NAME|VAL|MATRIX|MEM|PRT|MULPRT|DISP|PLOT|CLIP|DECOMP|TELL|SHOW|MODEL|SIM|ENDO|EXO|UNFIX|CHECKOFF|ITERSHOW|SIGN|RUN|PIPE|INI|FUNCTION|RESET|CLS|FOR|IF|STOP|EXIT|ACCEPT|PAUSE|GOTO|TARGET|TABLE|MENU|OLS|R|R_FILE|R_EXPORT|R_RUN|HELP|EDIT|SYS|param|cell|dates|attend|cols|rows|names|colors)\b</string>
			<key>name</key>
			<string>keyword.commands1.gekko</string>
		</dict>
		<key>linecomment</key>
		<dict>
			<key>match</key>
			<string>(//).*\n?</string>
			<key>name</key>
			<string>comment.line.gekko</string>
		</dict>
		<key>math</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(ABS|ARCCOS|ARCSIN|ARCTAN|ARCTAN2|BETA|BETAREG|BINOMIAL|BOOL_(AND|EQV|IMP|NOT|OR|XOR)|CEIL|CENTROPY|COS|COSH|CVPOWER|DIV|DIV0|EDIST|ENTROPY|ERRORF|EXECSEED|EXP|FACT|FLOOR|FRAC|GAMMA|GAMMAREG|IFTHEN|LOG|LOG2|LOG10|LOGBETA|LOGGAMMA|MAPVAL|MAX|MIN|MOD|NCP(CM|F|VUPOW|VUSIN)|NORMAL|PI|POLY|POWER|RANDBINOMIAL|RANDLINEAR|RANDTRIANGLE|ROUND|RPOWER|SIGMOID|SIGN|SIGNPOWER|SIN|SINH|SL(EXP|LOG10|REC)|SQ(EXP|LOG10|R|REC|RT)|TANH?|TRUNC|UNIFORM|UNIFORMINT|VCPOWER)\b</string>
			<key>name</key>
			<string>keyword.operator.gms</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>(?&lt;![\d.])\b\d+(\.\d+)?([eE]-?\d+)?|\.\d+([eE]-?\d+)?</string>
			<key>name</key>
			<string>constant.numeric.gms</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>match</key>
			<string>(\b(and|or|not)\b)|(\+|-|%|#|\*|\/|\*\*|=|&lt;=?|&gt;=?)</string>
			<key>name</key>
			<string>keyword.operator.gams</string>
		</dict>
		<key>singlequotestring</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.gms</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.gms</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.gms</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>%(\w+%|\d+)</string>
					<key>name</key>
					<string>entity.name.class.gms</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.gekko</string>
	<key>uuid</key>
	<string>5da02451-1da1-449b-93c5-fd95759f6265</string>
</dict>
</plist>
